module.exports = {
  theme: {
    fontFamily: {
      Inter: ["Inter", "sans-serif"],
    },
    colors: {
      frostee: "#E7F7E9",
      palma: "#11AB20",
      "chinese-white": "#DFE4DF",
      cultured: "#F5FAF5",
      "dark-jungle-green": "#1E231E",
      penache: "#FAFDFA",
      corduroy: "#676967",
      tara: "#E8F9E9",
      malachite: "#14C425",
      "ripe-lemon": "#EDDC0C",
      "hint-of-yellow": "#FDFCE7",
      "provincial-pink": "#FCEAE6",
      "byzantine-blue": "#2D5BE0",
      perano: "#BECCF5",
      white: "#FFFFFF",
      "islamic-green": "#0F9C1D",
      "san-felix": "#0C7917",
      "granny-smith-apple": "#92D898",
      "fringy-flower": "#B5E5BA",
      "gray-asparagus": "#4D514D",
      "heavy-metal": "#212621",
      grenadier: "#E02C00",
    },
    fontSize: {
      xxs: ["0.625rem", { lineHeight: "1rem", letterSpacing: "0%" }],
      xs: ["0.75rem", { lineHeight: "1rem", letterSpacing: "0%" }],
      sm: [
        "0.875rem",
        { lineHeight: "1.25rem", letterSpacing: "0%" },
      ],
      base: ["1rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      lg: ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      xl: ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0%" }],
      "3xl": [
        "1.75rem",
        { lineHeight: "2.5rem", letterSpacing: "0%" },
      ],
      "4xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "0%" }],
      "5xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "0%" }],
      "6xl": ["3rem", { lineHeight: "3.5rem", letterSpacing: "0%" }],
      "7xl": ["3.5rem", { lineHeight: "4rem", letterSpacing: "0%" }],
      "8xl": ["4rem", { lineHeight: "4.5rem", letterSpacing: "0%" }],
      "9xl": ["4.5rem", { lineHeight: "5rem", letterSpacing: "0%" }],
    },
    extend: {
      maxWidth: {
        "1920": "1920px",
      },
      spacing: {
        "18": "4.5rem",
      },
      borderRadius: {},
    },
  },
};
