module.exports = {
  theme: {
    fontFamily: {
      Inter: ["Inter", "sans-serif"],
    },
    colors: {
      frostee: "#E7F7E9",
      palma: "#11AB20",
      "chinese-white": "#DFE4DF",
      cultured: "#F5FAF5",
      "dark-jungle-green": "#1E231E",
      penache: "#FAFDFA",
      corduroy: "#676967",
      dark_corduroy: "#6A6E6A",
      tara: "#E8F9E9",
      malachite: "#14C425",
      "ripe-lemon": "#EDDC0C",
      "hint-of-yellow": "#FDFCE7",
      "provincial-pink": "#FCEAE6",
      "byzantine-blue": "#2D5BE0",
      perano: "#BECCF5",
      white: "#FFFFFF",
      "islamic-green": "#0F9C1D",
      "san-felix": "#0C7917",
      "granny-smith-apple": "#92D898",
      "fringy-flower": "#B5E5BA",
      "gray-asparagus": "#4D514D",
      "heavy-metal": "#212621",
      grenadier: "#E02C00",
      mint_green: "#F8FCF8",
      saltpan: "#F7FBF7",
      tonal_dark_mercury: "#E9E9E9",
      ripe_lemon: "#EDDCOC",
    },
    fontSize: {
      xxs: ["0.625rem", { lineHeight: "1rem", letterSpacing: "0%" }],
      xs: ["0.75rem", { lineHeight: "1rem", letterSpacing: "0%" }],
      sm: [
        "0.875rem",
        { lineHeight: "1.25rem", letterSpacing: "0%" },
      ],
      base: ["1rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      lg: ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      xl: ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "0%" }],
      "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0%" }],
      "3xl": [
        "1.75rem",
        { lineHeight: "2.5rem", letterSpacing: "0%" },
      ],
      "4xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "0%" }],
      "5xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "0%" }],
      "6xl": ["3rem", { lineHeight: "3.5rem", letterSpacing: "0%" }],
      "7xl": ["3.5rem", { lineHeight: "4rem", letterSpacing: "0%" }],
      "8xl": ["4rem", { lineHeight: "4.5rem", letterSpacing: "0%" }],
      "9xl": ["4.5rem", { lineHeight: "5rem", letterSpacing: "0%" }],
    },
    extend: {
      maxWidth: {
        "1920": "1920px",
      },
      spacing: {
        "18": "4.5rem",
      },
      boxShadow: {
        variant1: "0px 3px 10px 0px rgba(223, 228, 223, 0.25);",
        variant2: "0px 2px 2px 0px rgba(0, 0, 0, 0.05);",
        variant3: "0px 3px 10px 0px rgba(29, 184, 18, 0.10);",
        variant4: "0px 8px 16px -8px rgba(0, 0, 0, 0.05);",
      },
      borderWidth: {
        "0.5": "0.5px",
      },
      borderRadius: {
        "4xl": "3.125rem",
      },
      inset: {
        calc: "calc(50% - 50px)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
